name: Code checks

on:
  workflow_dispatch:

jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenv-in-project: true
        virtualenv-path: .venv
        installer-paraller: true

    - name: Install Dependencies
      run: |
        poetry env use python
        source .venv/bin/activate
        poetry install 
    - name: Run linting tests
      run: | 
        poetry run flake8 src/model/
    - name: Run unit tests
      run: |
        poetry run pytest tests/test_train.py


